version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017" 
    networks:
      - reviews-api-app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8086:8086
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - reviews-api-app-network

networks:
  reviews-api-app-network:

volumes:
  mongodb-data:
